"""initial schema

Revision ID: 448d0e112242
Revises: 
Create Date: 2026-09-21 23:39:47.812215
"""
from __future__ import annotations

import sqlalchemy as sa

from alembic import op

revision = '448d0e112242'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('source_system', sa.String(length=64), nullable=False),
    sa.Column('owner_role', sa.String(length=64), nullable=False),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assets_code'), ['code'], unique=True)

    op.create_table('audit_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_events_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_ts'), ['ts'], unique=False)

    op.create_table('models',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('model_id', sa.String(length=80), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('pinned', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_id')
    )
    op.create_table('rules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('regulator', sa.String(length=32), nullable=False),
    sa.Column('citation', sa.String(length=200), nullable=False),
    sa.Column('applies_to', sa.JSON(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rules_code'), ['code'], unique=True)

    op.create_table('scans',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('idempotency_key', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stats', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_table('transcripts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('corpus_hash', sa.String(length=64), nullable=False),
    sa.Column('product_line', sa.String(length=16), nullable=False),
    sa.Column('synthetic', sa.Boolean(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('labels', sa.JSON(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transcripts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transcripts_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_transcripts_corpus_hash'), ['corpus_hash'], unique=False)

    op.create_table('workflows',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workflows', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workflows_code'), ['code'], unique=True)

    op.create_table('asset_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('asset_id', sa.String(length=36), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('content_text', sa.Text(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scan_id', sa.String(length=36), nullable=True),
    sa.Column('fetch_mode', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id', 'content_hash', name='uq_asset_content')
    )
    with op.batch_alter_table('asset_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_asset_versions_asset_id'), ['asset_id'], unique=False)

    op.create_table('contracts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('rule_id', sa.String(length=36), nullable=True),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('severity', sa.String(length=8), nullable=False),
    sa.Column('owner_role', sa.String(length=64), nullable=False),
    sa.Column('check', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contracts_code'), ['code'], unique=True)

    op.create_table('prompt_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workflow_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=80), nullable=False),
    sa.Column('prompt_hash', sa.String(length=64), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('author', sa.String(length=64), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('encodes_rule_versions', sa.JSON(), nullable=False),
    sa.Column('asset_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workflow_id', 'version', name='uq_prompt_version')
    )
    with op.batch_alter_table('prompt_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prompt_versions_prompt_hash'), ['prompt_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_prompt_versions_workflow_id'), ['workflow_id'], unique=False)

    op.create_table('rule_source_checks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('rule_id', sa.String(length=36), nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('excerpt', sa.Text(), nullable=False),
    sa.Column('fetch_mode', sa.String(length=16), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('changed', sa.Boolean(), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rule_source_checks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rule_source_checks_rule_id'), ['rule_id'], unique=False)

    op.create_table('rule_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('rule_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('clause_text', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('change_classification', sa.String(length=32), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('disputed', sa.Boolean(), nullable=False),
    sa.Column('dispute_note', sa.Text(), nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=False),
    sa.Column('git_commit', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['rules.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rule_id', 'version', name='uq_rule_version')
    )
    with op.batch_alter_table('rule_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rule_versions_rule_id'), ['rule_id'], unique=False)

    op.create_table('scan_artifacts',
    sa.Column('scan_id', sa.String(length=36), nullable=False),
    sa.Column('asset_id', sa.String(length=36), nullable=False),
    sa.Column('outcome', sa.String(length=24), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ),
    sa.PrimaryKeyConstraint('scan_id', 'asset_id')
    )
    op.create_table('contract_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('contract_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('spec', sa.JSON(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('judge_model_id', sa.String(length=80), nullable=True),
    sa.Column('n_runs', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contract_id', 'version', name='uq_contract_version')
    )
    with op.batch_alter_table('contract_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contract_versions_contract_id'), ['contract_id'], unique=False)

    op.create_table('rule_asset_edges',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('rule_version_id', sa.String(length=36), nullable=False),
    sa.Column('asset_id', sa.String(length=36), nullable=False),
    sa.Column('asset_version_id', sa.String(length=36), nullable=True),
    sa.Column('polarity', sa.String(length=16), nullable=False),
    sa.Column('evidence_span', sa.Text(), nullable=False),
    sa.Column('span_offset', sa.Integer(), nullable=False),
    sa.Column('detection', sa.String(length=16), nullable=False),
    sa.Column('matcher', sa.String(length=64), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('confirmed_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['asset_version_id'], ['asset_versions.id'], ),
    sa.ForeignKeyConstraint(['rule_version_id'], ['rule_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rule_version_id', 'asset_id', 'evidence_span', name='uq_edge_span')
    )
    with op.batch_alter_table('rule_asset_edges', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rule_asset_edges_asset_id'), ['asset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rule_asset_edges_rule_version_id'), ['rule_version_id'], unique=False)

    op.create_table('runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_key', sa.String(length=160), nullable=False),
    sa.Column('workflow_id', sa.String(length=36), nullable=False),
    sa.Column('prompt_version_id', sa.String(length=36), nullable=False),
    sa.Column('model_id', sa.String(length=36), nullable=False),
    sa.Column('adapter', sa.String(length=16), nullable=False),
    sa.Column('corpus_hash', sa.String(length=64), nullable=False),
    sa.Column('contract_set_hash', sa.String(length=64), nullable=False),
    sa.Column('rule_date', sa.Date(), nullable=False),
    sa.Column('trigger', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('gate', sa.String(length=8), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stats', sa.JSON(), nullable=False),
    sa.Column('requested_by', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ),
    sa.ForeignKeyConstraint(['prompt_version_id'], ['prompt_versions.id'], ),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_runs_run_key'), ['run_key'], unique=True)

    op.create_table('run_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('transcript_id', sa.String(length=36), nullable=False),
    sa.Column('contract_version_id', sa.String(length=36), nullable=False),
    sa.Column('outcome', sa.String(length=8), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['contract_version_id'], ['contract_versions.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.ForeignKeyConstraint(['transcript_id'], ['transcripts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'transcript_id', 'contract_version_id', name='uq_result')
    )
    with op.batch_alter_table('run_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_run_results_contract_version_id'), ['contract_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_run_results_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_run_results_transcript_id'), ['transcript_id'], unique=False)

    op.create_table('workflow_outputs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('transcript_id', sa.String(length=36), nullable=False),
    sa.Column('output', sa.JSON(), nullable=False),
    sa.Column('route', sa.String(length=8), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('usage', sa.JSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.ForeignKeyConstraint(['transcript_id'], ['transcripts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'transcript_id', name='uq_output_run_transcript')
    )
    with op.batch_alter_table('workflow_outputs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workflow_outputs_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_outputs_transcript_id'), ['transcript_id'], unique=False)

    op.create_table('review_tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('dedupe_key', sa.String(length=200), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('rule_version_id', sa.String(length=36), nullable=True),
    sa.Column('asset_id', sa.String(length=36), nullable=True),
    sa.Column('edge_id', sa.String(length=36), nullable=True),
    sa.Column('run_result_id', sa.String(length=36), nullable=True),
    sa.Column('staleness_direction', sa.String(length=24), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('assignee_role', sa.String(length=64), nullable=False),
    sa.Column('reason_code', sa.String(length=48), nullable=True),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('decided_by', sa.String(length=64), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['edge_id'], ['rule_asset_edges.id'], ),
    sa.ForeignKeyConstraint(['rule_version_id'], ['rule_versions.id'], ),
    sa.ForeignKeyConstraint(['run_result_id'], ['run_results.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dedupe_key', name='uq_review_dedupe')
    )
    op.create_table('test_cases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('review_task_id', sa.String(length=36), nullable=False),
    sa.Column('contract_id', sa.String(length=36), nullable=False),
    sa.Column('transcript_id', sa.String(length=36), nullable=True),
    sa.Column('expected', sa.JSON(), nullable=False),
    sa.Column('reason_code', sa.String(length=48), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('approver', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.ForeignKeyConstraint(['review_task_id'], ['review_tasks.id'], ),
    sa.ForeignKeyConstraint(['transcript_id'], ['transcripts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('test_cases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_test_cases_review_task_id'), ['review_task_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_cases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_test_cases_review_task_id'))

    op.drop_table('test_cases')
    op.drop_table('review_tasks')
    with op.batch_alter_table('workflow_outputs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workflow_outputs_transcript_id'))
        batch_op.drop_index(batch_op.f('ix_workflow_outputs_run_id'))

    op.drop_table('workflow_outputs')
    with op.batch_alter_table('run_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_run_results_transcript_id'))
        batch_op.drop_index(batch_op.f('ix_run_results_run_id'))
        batch_op.drop_index(batch_op.f('ix_run_results_contract_version_id'))

    op.drop_table('run_results')
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_runs_run_key'))

    op.drop_table('runs')
    with op.batch_alter_table('rule_asset_edges', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rule_asset_edges_rule_version_id'))
        batch_op.drop_index(batch_op.f('ix_rule_asset_edges_asset_id'))

    op.drop_table('rule_asset_edges')
    with op.batch_alter_table('contract_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contract_versions_contract_id'))

    op.drop_table('contract_versions')
    op.drop_table('scan_artifacts')
    with op.batch_alter_table('rule_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rule_versions_rule_id'))

    op.drop_table('rule_versions')
    with op.batch_alter_table('rule_source_checks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rule_source_checks_rule_id'))

    op.drop_table('rule_source_checks')
    with op.batch_alter_table('prompt_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prompt_versions_workflow_id'))
        batch_op.drop_index(batch_op.f('ix_prompt_versions_prompt_hash'))

    op.drop_table('prompt_versions')
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contracts_code'))

    op.drop_table('contracts')
    with op.batch_alter_table('asset_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_asset_versions_asset_id'))

    op.drop_table('asset_versions')
    with op.batch_alter_table('workflows', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workflows_code'))

    op.drop_table('workflows')
    with op.batch_alter_table('transcripts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transcripts_corpus_hash'))
        batch_op.drop_index(batch_op.f('ix_transcripts_code'))

    op.drop_table('transcripts')
    op.drop_table('scans')
    with op.batch_alter_table('rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rules_code'))

    op.drop_table('rules')
    op.drop_table('models')
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_events_ts'))
        batch_op.drop_index(batch_op.f('ix_audit_events_event_type'))
        batch_op.drop_index(batch_op.f('ix_audit_events_entity_type'))
        batch_op.drop_index(batch_op.f('ix_audit_events_entity_id'))

    op.drop_table('audit_events')
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assets_code'))

    op.drop_table('assets')
    # ### end Alembic commands ###
